package:
  name: minced
  version: "0.2.0"

source:
  git_url: https://github.com/ctSkennerton/minced.git
  git_rev: 0.2.0

build:
  number: 0

test:
  files:
    - Aquifex_aeolicus_VF5.fna
    - Aquifex_aeolicus_VF5.expected
  commands:
    - minced -gff Aquifex_aeolicus_VF5.fna > Aquifex_aeolicus_VF5.output
    - diff -q Aquifex_aeolicus_VF5.output Aquifex_aeolicus_VF5.expected > /dev/null

about:
  summary: Mining CRISPRs in Environmental Datasets
  home: https://github.com/ctSkennerton/minced
  license: GPL3
  license_file: LICENSE
