package:
  name: infernal
  version: "1.1.1"

source:
  fn: infernal-1.1.1.tar.gz
  url: http://selab.janelia.org/software/infernal/infernal-1.1.1.tar.gz
 
requirements:
  build:
    - gcc
 
test:
  commands:
    - cmbuild -h
 
about:
  summary: Infernal ("INFERence of RNA ALignment") is for searching DNA sequence databases for RNA structure and sequence similarities.
  home: http://infernal.janelia.org/
  license: GPL3
  license_file: LICENSE
